@extends('layouts.layout')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Je profiel</div>

                    <div class="card-body">
                        Hieronder kun je je gegevens bewerken.<hr>
                        {!! Form::open(['url' => '/profile/edit']) !!}
                        <!-- CSRF Token generated by this method automatically -->
                        {{Form::label('firstname', 'Voornaam')}}
                        {{Form::text('firstname', Auth::user()->firstname)}}

                        {{Form::label('lastname', 'Achternaam')}}
                        {{Form::text('lastname', Auth::user()->lastname)}}

                        {{Form::label('housenumber', 'Huisnummer')}}
                        {{Form::text('housenumber', Auth::user()->housenumber)}}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
