@extends('layouts.layout')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Je profiel</div>

                    <div class="card-body">
                        Hieronder kun je je gegevens bewerken.<hr>
                    {{Form::model($user, ['route' => ['profile_update', $user->id], 'method' => 'PUT'])}}
                    <!-- CSRF Token generated by this method automatically -->
                        <div class="form group">
                            {{Form::label('firstname', 'Voornaam')}}
                            {{Form::text('firstname', $user->firstname) }}
                        </div>

                        <div class="form group">
                            {{Form::label('lastname', 'Achternaam')}}
                            {{Form::text('lastname', $user->lastname)}}
                        </div>

                        <div class="form group">
                            {{Form::label('housenumber', 'Huisnummer')}}
                            {{Form::text('housenumber', $user->housenumber)}}
                        </div>

                        <div class="form group">
                            {{Form::label('email', 'E-Mail adres')}}
                            {{Form::text('email', $user->email)}}
                        </div>

                        {{Form::submit('Bijwerken', ['class' => 'btn btn-primary'])}}

                        {!! Form::close() !!}
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection
